services:
  - type: web
    name: lioraxai
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn lioraxai_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lioraxai_project.settings_render
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: lioraxai_db
          property: connectionString

databases:
  - name: lioraxai_db
    databaseName: lioraxai
    user: lioraxai
    plan: free 